// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xszzuacjiieyimhoclli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzenp1YWNqaWlleWltaG9jbGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTY4NzcsImV4cCI6MjA1OTM3Mjg3N30.dJGmecpD6TaBC3gcy0mD9RLdtpQrYoRASdRnR_fS4XU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);